name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Xorg dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install xorg-dev
    
    - name: Build on ${{ matrix.os }}
      run: cargo build --verbose